version: '3.3'

services:
  app:
    build: .
    container_name: app
    volumes:
      - .:/app:rw # map data and files from parent directory in host to microservice directory in docker container
    env_file:
      - .env
    ports:
      - "80:8000"
    expose:
      - "80"
    command: make run
    restart: always
